include ./nord.conf
 font_family      Iosevka Fixed Extended
 bold_font        Iosevka Fixed Extended Bold
 italic_font      Iosevka Fixed Extended Italic
 bold_italic_font Iosevka Fixed Extended Bold Italic
font_size 11.0
window_padding_width 10
background_opacity 0.9
map F8 launch --location=hsplit
map F9 launch --location=vsplit
map F10 layout_action rotate
map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down
map ctrl+left resize_window narrower 3
map ctrl+right resize_window wider 3
map ctrl+up resize_window taller 3
map ctrl+down resize_window shorter 3
map ctrl+backspace send_text all \x17
map ctrl+tab no_op
map ctrl+shift+tab no_op
